# Generated by Django 2.0 on 2017-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierID', models.IntegerField()),
                ('CompanyName', models.CharField(max_length=40)),
                ('ContactName', models.CharField(max_length=30)),
                ('ContactTitle', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=60)),
                ('City', models.CharField(max_length=15)),
                ('Region', models.CharField(max_length=15)),
                ('PostalCode', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=15)),
            ],
        ),
    ]
