# Generated by Django 2.0 on 2017-12-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='SupplierID',
            field=models.IntegerField(unique=True),
        ),
    ]
